name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - main
    paths:
      - '!README.md'


jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: install clang-12
      run: sudo apt-get install -y clang-12 llvm-12-dev libc++-12-dev libc++abi-12-dev libunwind-12-dev

    - name: configure
      run: CC=clang-12 CXX=clang++-12 cmake -B ${{ github.workspace }}/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install

    - name: build
      run: CC=clang-12 CXX=clang++-12 cmake --build ${{ github.workspace }}/build

    - name: install
      run: CC=clang-12 CXX=clang++-12 cmake --install ${{ github.workspace }}/build

    - name: install lit
      run: pip install lit

    - name: test
      run: lit --verbose tests
      working-directory: ${{ github.workspace }}/build
